name = "SMLMFrameConnection"
uuid = "1517b1a9-81e8-461f-b994-92eb29599690"
authors = ["klidke@unm.edu"]
version = "0.4.0"

[deps]
Hungarian = "e91730f6-4275-51fb-a7a0-7064cfbd3b39"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
SMLMData = "5488f106-40b8-4660-84c5-84a168990d1b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
Hungarian = "0.6, 0.7"
NearestNeighbors = "0.4"
Optim = "1, 2"
SMLMData = "0.6"
StatsBase = "0.33, 0.34"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
